name: Build, Test and Publish @draftbit/web

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

defaults:
  run:
    working-directory: packages/web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit`
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Release next NPM package
        if: github.event_name == 'pull_request'
        run: |
          npm version prerelease --preid rc-$(git rev-parse --short HEAD) -no-git-tag-version
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JIGSAW_AUTH_TOKEN }}

      - name: Release NPM package
        if: github.event_name != 'pull_request'
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JIGSAW_AUTH_TOKEN }}
